### ISSUE TITLE
Get-Keystrokes.ps1 make the CPU to High

### ISSUE THREAD

**Issue by coldalfred** [PowerShellMafia/PowerSploit#103]
When i execute as default or -PollingInterval 100 or 10000 or 40 that is the default,

make the Powershell process consume a lot of CPU that is normal?

**Comment by mattifestation** [comment]
Yes, this is a known issue that unfortunately cannot be avoided due to the frequency in which GetAsyncKeyState is called. SetWindowsHookEx would make for a much better keylogger but that would require placing a DLL on disk.
