### ISSUE TITLE
Want to perform an interactive logon

### ISSUE THREAD

**Issue by ananthonline** [PowerShellMafia/PowerSploit#116]
I want to perform an interactive logon (as if a user entered credentials) by running a powershell command when the workstation is locked.

```
Import-Module C:\Temp\Invoke-CredentialInjection.ps1
Invoke-CredentialInjection -DomainName "my-machinename" -UserName "administrator" -Password "<password here>" -ExistingWinLogon -LogonType Interactive -AuthPackage Msv1_0
```

Running the following command using a remote Powershell execution mechanism that runs as SYSTEM gives me the output

> DLL OUTPUT: Logon succeeded, impersonating the token so it can be kidnapped and starting an infinite loop with the thread.

But I can still see the lock screen (using VNC, which mirrors the current console session). How do I interactively log onto the machine using this powershell cmdlet?

Thanks!

**Comment by mattifestation** [comment]
For this one, I defer to @clymb3r. @HarmJ0y, do you have any input on this?

**Comment by leechristensen** [comment]
You cannot use this cmdlet, or any other PowerSploit cmdlet, to unlock the workstation.  The purpose of Invoke-CredentialInjection is to create an access token which then can be stolen, impersonated, and used to access other resources.  "Interactive" refers to the type of token that is created.  If you're unfamiliar with tokens, I suggest you read up on how Windows handles authentication and token management.  The following resources may be of use:

http://blog.cobaltstrike.com/2015/12/16/windows-access-tokens-and-alternate-credentials/
https://technet.microsoft.com/en-us/library/bb457114.aspx

To accomplish what you want to do via PowerShell would require creating some new custom code which PowerSploit currently does not have.  To accomplish what you're wanting to do, consider tunneling your VNC traffic using a socks proxy (Meterpreter and Cobalt Strike have this capability).

**Comment by clymb3r** [comment]
Well, Lee just beat me to the punch as I was typing out a response :). As noted, this script creates logons that you can then impersonate.

Normally, if you had a plain text password and tried to pivot with it, things might look suspicious in the event log. Example: backdoor.exe just did an explicit credential logon as UserA. 

With this script, you can inject in to another process like winlogon that process user credentials all the time and do the logon. Then from your backdoor process, you can simply impersonate this token and pivot away. This doesn't look as suspicious in the event logs from personal experience.

**Comment by mattifestation** [comment]
Thanks for your input, gents!
