### ISSUE TITLE
Invalid Identifier

### ISSUE THREAD

**Issue by sylcvqnr** [PowerShellMafia/PowerSploit#123]
I manually set the Path, Interval and EndTime
```
$Path = "$env:temp\results"
$interval = 30
$EndTime = "23:50"
```
And  sometimes I get this error
```
Exception calling "CopyFromScreen" to "3" argument (s): "Invalid identifier"
In C:\Users\username\AppData\Roaming\GetTimeScreenshot.ps1: 9 character: 39
+	 $ Drawing Graphics.CopyFromScreen <<< <($ ScreenBounds.Location [drawin g.Point] :: Empty, $ ScreenBounds.Size)
	 + CategoryInfo: NotSpecified: (:) [], MethodInvocationException
	 + FullyQualifiedErrorId: DotNetMethodException
```

**Comment by mattifestation** [comment]
I can't support issues from modified versions of PowerSploit code. Can you replicate on the latest version  of Get-TimedScreenshot in the dev branch?

**Comment by sylcvqnr** [comment]
Sorry, I did not get it. Do you want me to make a pull request with my code or open an issue in dev branch? If it the issue in dev branch, how do I make that?
