### ISSUE TITLE
Invoke Mimikatz DCSYNC random crash

### ISSUE THREAD

**Issue by c1rcl3s** [PowerShellMafia/PowerSploit#124]
There is a bug in invoke-mimikatz - dcsync specifically. 

When called in a bat script for a large number of users , it crashes powershell **on very specific users**. The error "Powershell has stopped working" is displayed. No reasons given. 

Event Log shows exception value 0xc0000005.  

I did a bunch of things to troubleshoot: 

1. I thought it was a memory issue but it's not. I increased the powershell cmdlet memory size to 4096 and monitored the powershell process. It doesn't max out cycles or anything. 

2. I took the offending username on the crash and ran it individually , as admin, in another powershell process by explicitly specifying all the arguments for Invoke-Mimikatz dcsync and it still causes a crash. Just to iterate, other usernames work perfectly. It's only an issue with certain usernames. 

3. I managed , on one random try, to get an output from dcsync on one of the offending usernames. Turns out that it isn't able to pull supplemental credentials section of dcsync output. At this point, I assume the inability to parse whatever is returned to the script causes the crash. 

Do let me know if you need any more information or if you have encountered something like this. 

Thank you.

**Comment by mattifestation** [comment]
I seldom use Invoke-Mimikatz so I can't say I've encountered anything like that. In order to know if it's a problem with mimikatz, Invoke-Mimikatz, or Invoke-ReflectivePEInjection, I would need you to provide detailed reproduction steps. I just don't have enough information to triage the bug.
