### ISSUE TITLE
Get-NetGPOGroup erroneous MemberOf definition

### ISSUE THREAD

**Issue by Meatballs1** [PowerShellMafia/PowerSploit#127]
The Get-NetGPOGroup assumes that if no 'memberOf' is set then we assume local admins.

However this is not true.

Restricted groups can perform one of two actions. Either a user is added to a group (members), or a group is added to another group (memberof).

In this example a user is added to a group (local admins), but the local admins group is not added to any other groups on the device.

```
PS C:\Users\Administrator> $inf.GroupMembership

*S-1-5-32-544__Memberof                                                              *S-1-5-32-544__Members                                                              
-----------------------                                                              ----------------------                                                              
                                                                                     *S-1-5-21-3469583980-2692176441-4150475799-1119       
```

The output from Get-NetGPOGroup however automatically assumes memberOf local admins. But I think this is more due to a misunderstanding?

```
PS C:\Users\Administrator> Get-NetGPOGroup


Filters        : 
GPOName        : {08AC249E-7A77-4510-9C5E-6A16C1E60125}
GPOPath        : \\test.lab\SysVol\test.lab\Policies\{08AC249E-7A77-4510-9C5E-6A16C1E60125}
Members        : {S-1-5-21-3469583980-2692176441-4150475799-1119}
MemberOf       : {S-1-5-32-544}
GPODisplayName : WorkstationGPO
```

If we take the scenario of enumerating local admin membership, we only care about the members column, we dont care what other groups local admins are added to. We need to check the property name (e.g. S-1-5-32-544__Members) to find out what group people are being added to. Not the memberOf value.

**Comment by Meatballs1** [comment]
There is also a bit of a parsing error if it is not a well known SID group:

```
BobsGroup__Memberof =
BobsGroup__Members = Workstation Admins
```

```
Filters        : 
GPOName        : {08AC249E-7A77-4510-9C5E-6A16C1E60125}
GPOPath        : \\test.lab\SysVol\test.lab\Policies\{08AC249E-7A77-4510-9C5E-6A16C1E60125}
Members        : {S-1-5-21-3469583980-2692176441-4150475799-1119, Workstation Admins}
MemberOf       : {, }
GPODisplayName : WorkstationGPO
```

**Comment by Meatballs1** [comment]
Also if you set multiple members:

```
*S-1-5-32-544__Members = *S-1-5-21-3469583980-2692176441-4150475799-1119,Steve
```

**Comment by Meatballs1** [comment]
N.b. my code looks something like this (not returning anything at the mo) - but I'm not working on this function at the moment so no PR yet!

```
          if ($Inf.GroupMembership) {
                $Members = @()
                $Inf.GroupMembership | Get-Member *Members | ForEach-Object {
                    if ($_.Name.IndexOf('*') -eq 0) {
                        $group_sid = $_.Name.trim('*').trim('__Members')
                        $group = $script:sid_lookup.Get_Item($group_sid)
                    } else {
                        $group = $_.Name.trim('__Members')
                    }

                    if ($Inf.GroupMembership.($_.name) -is [system.array]) {
                        $Inf.GroupMembership.($_.name) | ForEach-Object {
                            if ($_.IndexOf('*') -eq 0) {
                                $user_sid = $_.trim('*')
                                $user = $script:sid_lookup.Get_Item($user_sid)
                            } else {
                                $user = $_
                            }
                       }
                    } else {
                        $u = $Inf.GroupMembership.($_.name)
                        if ($u.IndexOf('*') -eq 0) {
                            $user_sid = $u.trim('*')
                            $user = $script:sid_lookup.Get_Item($user_sid)
                        } else {
                            $user = $u
                        }
                    }
                }
            }
```

**Comment by HarmJ0y** [comment]
Another good catch.

Are you planning on submitting this as a PR at some point, or should I dive in and try to make the corrections?

**Comment by Meatballs1** [comment]
I haven't got anything lined up at the moment, my file deviates from `dev` in a number of ways at the moment!

**Comment by HarmJ0y** [comment]
Checking back in- was this fixed with your pull at https://github.com/PowerShellMafia/PowerSploit/pull/140 ? Or is there still work to be done.

**Comment by Meatballs1** [comment]
I think #140 just fixed GPP parsing. This is more to do with the RestrictedGroups parsing

**Comment by HarmJ0y** [comment]
OK, so this should be fixed with https://github.com/PowerShellMafia/PowerSploit/commit/f6ee5cb92ee7c037e57f5b09bc01340efea59283.

I **believe** that Get-NetGPOGroup should now handle multiple members in membersof, and the **-ResolveMemberSIDs** flag for it should try to resolve any member names to SIDs correctly. 

GptTmpl.inf parsing in **Get-GptTmpl** now uses Get-IniContent. The logic for **Find-GPOLocation** was heavily rewritten and I believe should finally be accurate.

I'm going to close this for now, but if you confirm that there's still an issue with the new code please reopen it and I'll investigate further.

**Comment by HarmJ0y** [comment]
Example:

<img width="637" alt="get_net_gpogroup" src="https://cloud.githubusercontent.com/assets/5504523/15843340/5da026de-2c16-11e6-833a-bc21b19171e2.png">

<img width="636" alt="find_gpo_location" src="https://cloud.githubusercontent.com/assets/5504523/15843343/63ee8ada-2c16-11e6-92b5-a99707e2be4c.png">

Looks like it handles members/memberof properly, multiple accounts, regular user names vs. SIDs, and 'restricted groups' vs groups.xml :)
