### ISSUE TITLE
PowerView DomainSearcher Memory Issues

### ISSUE THREAD

**Issue by Meatballs1** [PowerShellMafia/PowerSploit#130]
By default Get-DomainSearcher creates a DirectorySearcher with .CacheResults = true

This is probably not expected as we dont do any second searchs on the items? Changing this to false should save some memory.

Additionally the `FindAll()` method has the following note:

>Due to implementation restrictions, the SearchResultCollection class cannot release all of its unmanaged resources when it is garbage collected. To prevent a memory leak, you must call the Dispose method when the SearchResultCollection object is no longer needed.

Thing is, if you want to dispose of the SearchResultCollection you need to put it in a variable, as there is no `using` syntax
e.g.

```
$res = $ds.FindAll()
$res | For-EachObject { blah}
$res.Dispose()
```

I'm not sure if that nullifies the memory benefits of pipelining? 

EDIT: Should now do:

```
try {
    $res = $ds.FindAll()
    $res  | For-EachObject { blah}
catch { blah}
finally { $res .Dispose() }
```

**Comment by secabstraction** [comment]
Matt would probably say, "Time to fire up a debugger and have a look." I'd
put my money on the DirectorySearcher not recursively disposing its child
objects, especially since MSFT documented the potential memory leak.
Storing the SearchResultCollection in a variable does nullify the benefits
of pipelining, it would be faster to:

$res = $ds.FindAll()
foreach ($result in $res) { blah $result }
$res.Disopse()

**Comment by secabstraction** [comment]
Matt would probably say, "Time to fire up a debugger and have a look." I'd put my money on the DirectorySearcher not recursively disposing its child objects, especially since MSFT documented the potential memory leak. Storing the SearchResultCollection in a variable does nullify the benefits of pipelining, it would be faster to: 
```powershell 
$res = $ds.FindAll() 
foreach ($result in $res) { blah $result } 
$res.Disopse() 
```

**Comment by Meatballs1** [comment]
Yeah looks like it needs to be disposed on the object itself:

```
PS C:\Users\Administrator> $a=Get-DomainSearcher

PS C:\Users\Administrator> $z = $a.FindAll()

PS C:\Users\Administrator> $a.Dispose()

PS C:\Users\Administrator> $a.Disposed

PS C:\Users\Administrator> $z

Path                                                                                                                             Properties                                                                                                                      
----                                                                                                                             ----------                                                                                                                      
LDAP://DC=test,DC=lab                                                                                                            {ridmanagerreference, objectcategory, msds-nctype, systemflags...}                                                              
LDAP://CN=Users,DC=test,DC=lab                                                                                                   {usnchanged, showinadvancedviewonly, whencreated, description...}      
```

The area I'm not sure about is whether saving the results to a variable, causes everything to be retrieved at that instant, or whether it only gets retrieved from LDAP/Underlying ADSI memory when the enumerator is used. I think Wireshark may do the trick :)

**Comment by secabstraction** [comment]
Yeah, I don't know that one off the top of my head.

**Comment by Meatballs1** [comment]
Looks like it only pulls down the data when the enumerator is accessed:

```
PS C:\Users\mrt\Documents> $a = Get-DomainSearcher
PS C:\Users\mrt\Documents> $src = $a.FindAll()
PS C:\Users\mrt\Documents> $src.Dispose()
PS C:\Users\mrt\Documents> $a.Dispose()
PS C:\Users\mrt\Documents> $a = Get-DomainSearcher
PS C:\Users\mrt\Documents> $src = $a.FindAll()
PS C:\Users\mrt\Documents> "Some binding traffic perform"
Some binding traffic perform
PS C:\Users\mrt\Documents> $enum = $src.GetEnumerator()
PS C:\Users\mrt\Documents> $enum.Current
PS C:\Users\mrt\Documents> $enum.MoveNext()
True
PS C:\Users\mrt\Documents> $enum.Current

Path                                    Properties
----                                    ----------
LDAP://DC=test,DC=lab                   {fsmoroleowner, minpwdlength, adspat...
```

Traffic only really started with `MoveNext()`

**Comment by HarmJ0y** [comment]
What about something like this:

```powershell
$res = $UserSearcher.FindAll()
$UserSearcher.FindAll() | Where-Object {$_} | ForEach-Object {
    # convert/process the LDAP fields for each result
    Convert-LDAPProperty -Properties $_.Properties
}
$res.dispose()
$UserSearcher.dispose()
```

Wireshark seems to confirm what @Meatballs1 said- minimal traffic on the findall(), 'real' traffic/results on the pipeline processing.

**Comment by Meatballs1** [comment]
yarp but I presume you want:

```
$res = $UserSearcher.FindAll()
$res | Where-Object {$_} | ForEach-Object {
    # convert/process the LDAP fields for each result
    Convert-LDAPProperty -Properties $_.Properties
}
$res.dispose()
$UserSearcher.dispose()

**Comment by HarmJ0y** [comment]
Derp, correct. I'll try to add that in shortly and we'll see how it works.

**Comment by secabstraction** [comment]
Is the empty where clause needed to pull from AD? Seems like you could just do:
```powershell
$res = $UserSearcher.FindAll()
$res | foreach {
    Convert-LDAPProperty -Properties $_.Properties
}
$res.Dispose()
$UserSearcher.Dispose()
```
TODO: rebuild test domain, try it myself, manana

**Comment by HarmJ0y** [comment]
Pushed the changes to dev: https://github.com/PowerShellMafia/PowerSploit/commit/c52f9d712c7842f0318c821552501e9fde39740f

Set $Searcher.CacheResults = $False for Get-DomainSearcher, and added the dispose() approach to all functions I could see where it was applicable: Get-NetUser, Get-ObjectAcl/Add-ObjectAcl, Get-GUIDMap, Get-NetComputer, Get-ADObject, Get-NetOU, Get-NetSite, Get-NetSubnet, Get-NetGroup, Get-NetGroupMember, Get-DFSshare, Get-NetGPO, Get-NetDomainTrust

I ran through a quick test of those functions, but there may be issues or cmdlets I missed. After one of you are able to quickly test and confirm the code's OK, I'll close this issue.
