### ISSUE TITLE
Issues with invoke-tokenManipulation

### ISSUE THREAD

**Issue by jmaravi** [PowerShellMafia/PowerSploit#131]
I am in a powershell session as local admin, i have imported the module powersloit.psd1 in powershell as well. Whenever I try to run the module invoke-tokenmanipulation -Enumerate I see the following errors:
Get-Process : A parameter cannot be found that matches parameter name 'IncludeUserName'.
At C:\offensive-powershell\PowerSploit\Exfiltration\Invoke-TokenManipulation.ps1:1689 char:37
+         $SystemTokens = Get-Process -IncludeUserName | Where {$_.Username -eq $L ...
+                                     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetProcessCommand[...]

and then:

WARNING: Failed to get processes primary token. ProcessId: 2612. ProcessName armsvc. Error: 5
WARNING: Failed to get processes primary token. ProcessId: 3020. ProcessName CamMute. Error: 5
WARNING: Failed to get processes primary token. ProcessId: 2844. ProcessName conhost. Error: 5

finally the module list ONLY the token for my session but i dont see nt authority\system

**Comment by FuzzySecurity** [comment]
Hey jmaravi, see issue #112, this should be resolved now but I gather the fix is not in master?

https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/Invoke-TokenManipulation.ps1#L1689

**Comment by jmaravi** [comment]
same error using the module you mention.
Attached is the full error screenshot
[error.txt](https://github.com/PowerShellMafia/PowerSploit/files/232372/error.txt)

**Comment by HarmJ0y** [comment]
Did you try the development branch? Please confirm.

**Comment by mattifestation** [comment]
@HarmJ0y: Correct. This was fixed in the dev branch.
