### ISSUE TITLE
PowerUp unquoted path not found

### ISSUE THREAD

**Issue by evilgash** [PowerShellMafia/PowerSploit#137]
I think the WMI query for finding unquoted paths is not working correctly. If I run Get-ServiceUnquoted on my Windows 7 SP1 32Bit I do not get any results. However, if I run the following query:

```
PS C:\> Get-WmiObject win32_service | ?{$_.PathName -like '*Program*'} | select PathName

PathName
--------

"C:\Program Files\Google\Update\GoogleUpdate.exe" /svc
"C:\Program Files\Google\Update\GoogleUpdate.exe" /medsvc
C:\Program Files\Microsoft Office\Office14\GROOVE.EXE /auditservice
"C:\Program Files\Mozilla Maintenance Service\maintenanceservice.exe"
"C:\Program Files\Common Files\Microsoft Shared\Source Engine\OSE.EXE"
"C:\Program Files\Common Files\Microsoft Shared\OfficeSoftwareProtectionPlatform\OSPPSVC.EXE"
"C:\Program Files\Windows Media Player\wmpnetwk.exe"
```

I see that the 3rd service uses an unquoted path.

Additionally the following line:

`$Out | Add-Member Noteproperty 'AbuseFunction' "Write-ServiceBinary -ServiceName '$($Service.name)' -Path <HijackPath>"`

should be changed to:

`$Out | Add-Member Noteproperty 'AbuseFunction' "Write-ServiceBinary -ServiceName '$($Service.name)' -ServicePath <HijackPath>"`

**Comment by HarmJ0y** [comment]
Thanks for the catch, working on checking this out today along with some other PowerUp issues.

**Comment by mattifestation** [comment]
@HarmJ0y: Just for reference, here's what I did in CimSweep to normalize service binary paths. https://github.com/PowerShellMafia/CimSweep/blob/dev/CimSweep/Core/CoreFunctions.ps1#L2070-L2081

**Comment by HarmJ0y** [comment]
@mattifestation - for service path situations, I've seen a variety of forms- 'C:\blah.exe', '"C:\blah.exe" -i C:\temp\config.ini',  '"C:\blah.exe" -i "C:\temp\config.ini"', etc. I was trying to funnel everything in PowerUp that checks for a modifiable file through a common function that tries to handle all possible path/config file combinations - https://github.com/PowerShellMafia/PowerSploit/blob/c30c682797b2aaaa176b1329f346f45050d72261/Privesc/PowerUp.ps1#L18-L81

Obviously want to move towards an ACL approach soonish.

@evilgash - the push from 5 days ago should fix the edge case you had. I'm going to close this issue but if it remains please reopen it.
