### ISSUE TITLE
Credential bruteforce/test script needed

### ISSUE THREAD

**Issue by maaaaz** [PowerShellMafia/PowerSploit#142]
Hello to the Mafia,

It might sound dumb but I find that the framework lacks a **bruteforce script**, whose role would simply to test domain credentials provided in input files (1 file for logins + 1 file for passwords, or 1 combo file with a separator).
Really, it would be super useful, when you compromise a server but for **whatever reasons** you can't just have a route-trafficking meterpreter, or a specific tool, and you don't want to go through a **cheap `net use \\share /user:<login> <pass>` FOR loop**.

Using only the good old builtin powershell would be awesome.

Sorry if it is already possible and I just missed it.
Cheers!

**Comment by sunnyc7** [comment]
Hi Thomas
Why would you have a bruteforce script in the framework, when you can get
clear text passwords using Mimikatz ?

Thanks.

**Comment by maaaaz** [comment]
Well, I am absolutely not talking about collecting credentials (with mimikatz) but rather, to find a way to **bruteforce (other) credentials.**

I shall give you more insight about my basic need.
1. Let's say you managed to **find an account** that allowed you to connect, through RDP (the only visible service), on a targeted domain server member. That's cool.
2. You obviously want to **pivot from this host** as it gives you access to **more network services (especially 445)** on a bunch of member server...but too bad you just **can't install or use any third-party bruteforce tool** because either the engagement does not allow it or you don't have local admin rights on it (and no local privesc vuln, and applocker and so on...).
3. You still want to escalate your privileges by bruteforcing several privileged accounts from the pivot, as you have some insights of what their password could be, but **you can't go for a manual test.**

The need is really to have a `Invoke-CredentialForcer` function in PowerSploit to **iterate over a list of user and a list of password**, as you can't you easily bruteforce stuff without appropriate tool (and you don't want a cheap FOR loop).

The idea is really the same as of the `Invoke-Portscan`: have a common and general-purpose tool implemented in PowerShell :)

**Comment by sunnyc7** [comment]
Here is my argument.
a) Majority of Powersploit functions focus on stealth. Bruteforcing code is usually very noisy and defeats stealth.
b) Powersploit focuses on in-memory execution of stealth payloads. It's not easy to write in-memory bruteforce algorithms when you have to factor in huge dictionary's (in GB).
c) If you need to bruteforce a credential, you can dump NTLM hashes and use tools like oclHashcat against the dump. https://hashcat.net/oclhashcat/
d) For lateral movement, you can take a JoeBlo's account and do a privilege escalation using @HarmJ0y  Powerup.

I think sufficient alternatives exist for you to navigate your usecase, and hence, I dont see a merit for a bruteforcing function in Powersploit.

But, I will defer to @mattifestation for his thoughts on this.

thanks

**Comment by maaaaz** [comment]
Sunny, I do agree with all your points.
I'm closing that issue since the [`Invoke-BruteForce`](https://github.com/samratashok/nishang/blob/master/Scan/Invoke-BruteForce.ps1) fulfills my need.
