### ISSUE TITLE
Adding an extension column in the Invoke-FileFinder csv output

### ISSUE THREAD

**Issue by maaaaz** [PowerShellMafia/PowerSploit#143]
Hello to the Mafia,

Could it be possible to add a column showing the extension of found files into the csv output of `Invoke-FileFinder` ?
For huge lists it would surely help sorting.

Cheers!

**Comment by HarmJ0y** [comment]
After thinking it over, we decided against this as its not "standard" behavior and filters concerning extensions should be possible in a spreadsheet program.

**Comment by maaaaz** [comment]
Sure, but today the filter has to be applied against the full filename. Having only 1 specific column for it would have been great :(
