### ISSUE TITLE
PowerView.ps1 - Get-DomainTrust -Domain not always considered.

### ISSUE THREAD

**Issue by breakersall** [PowerShellMafia/PowerSploit#144]
Get-DomainTrust's -Domain parameter does not seem to respect the supplied value, and instead uses the default environment domain. The only time I could definitively get it to honor was using the API method, using the .net default and the LDAP it did not seem to value the passed content. 

I'm not 100% sure what is causing this, I looked at the code and didn't immediately see anything glaring.

**Comment by HarmJ0y** [comment]
I believe I know the issue (some block scoping stuff), should hopefully get a fix out soonish. What function were you testing, specifically?

**Comment by HarmJ0y** [comment]
Are you able to give us details on the exact function you're invoking that caused this error?
