### ISSUE TITLE
updating mimikatz... 

### ISSUE THREAD

**Issue by jun0s** [PowerShellMafia/PowerSploit#147]
I always update mimikatz, but since this change... "https://github.com/gentilkiwi/mimikatz/commit/81594553f72531aab2941267cfc6fc3392074efe"
(new sid module) 

this happens locally;

PS C:\Users\userxs> invoke-mimikatz
New function reference is null, this is almost certainly a bug in this script. Function: 73. Dll: WLDAP32.dll
En C:\Windows\system32\WindowsPowerShell\v1.0\Modules\powersploit\Exfiltration\Invoke-Mimikatz.ps1: 1714 Carácter: 7
+ ...             Throw "New function reference is null, this is almost cer ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (New function re...ll: WLDAP32.dll:String) [], RuntimeException
    + FullyQualifiedErrorId : New function reference is null, this is almost certainly a bug in this script. Function: 73. Dll: WLDAP32.dll

i solve this, by removing that "if sentence" from the code...

if ($NewThunkRef -eq $null -or $NewThunkRef -eq [IntPtr]::Zero)
					{
						Throw "New function reference is null, this is almost certainly a bug in this script. Function: $ProcedureName. Dll: $ImportDllPath"
					}

but i doubt it´s the right thing... i´m not a programmer.

 thank u guys!!

**Comment by gentilkiwi** [comment]
In fact, reflective script of @clymb3r does not really deal with ordinal imports... and LDAP functions are imported by imports.
But because he already made all the hard work, it's easy to fix :)

Around line 1690, replace
```
[IntPtr]$NewThunkRef = $Win32Functions.GetProcAddress.Invoke($ImportDllHandle, $ProcedureName)
```
by
```
if($ProcedureName -is [string])
{
	[IntPtr]$NewThunkRef = $Win32Functions.GetProcAddress.Invoke($ImportDllHandle, $ProcedureName)
}
else
{
	[IntPtr]$NewThunkRef = $Win32Functions.GetProcAddressOrdinal.Invoke($ImportDllHandle, $ProcedureName)
}
```

`Get-RemoteProcAddress` might have the problem too, but it does not seem to be used for local or remote powershell (only when the DLL is injected in another process than powershell)

**Comment by jun0s** [comment]
Thank you very much @gentilkiwi that works. :D

**Comment by gentilkiwi** [comment]
I'm not certain that this issue must be closed.
This could be the case when one of @clymb3r, @mattifestation or @HarmJ0y will have fixed the `Invoke-Mimikatz.ps1` script :)

![15pp5b](https://cloud.githubusercontent.com/assets/2307945/15991253/ab0831f0-30ad-11e6-8f60-908627011681.jpg)

**Comment by jun0s** [comment]
lol ....

**Comment by HarmJ0y** [comment]
@mattifestation is currently fixing the bug and updating Mimikatz to the latest release 👍

**Comment by mattifestation** [comment]
Updated lib https://github.com/PowerShellMafia/PowerSploit/commit/66c93f9317ffe64e08532e62acaadfcd1dea0d47
