### ISSUE TITLE
PowerSploit/Privesc/PowerUp.ps1 Write-ServiceBinary

### ISSUE THREAD

**Issue by xychix** [PowerShellMafia/PowerSploit#149]
The Write-ServiceBinary doesn't take a -Path value as documented, it takes a -ServicePath instead.

**Comment by HarmJ0y** [comment]
Thanks for the catch, fixed with https://github.com/PowerShellMafia/PowerSploit/commit/5d7fe6b10047f95ffdd8292419dec437c6e14244 in the dev branch.
