### ISSUE TITLE
Invoke-NinjaCopy: Errors on Windows 10 x64

### ISSUE THREAD

**Issue by okazymyrov** [PowerShellMafia/PowerSploit#152]
When I'm running 

``` powershell
Invoke-NinjaCopy -Path "C:\Windows\System32\config\SAM" -LocalDestination "$Env:TEMP\SAM"
```

as evaluated user on Windows 10 x64 the following errors occur

``` powershell
Specified cast is not valid.
At line:2208 char:7
+         if (($PEInfo.DllCharacteristics -band $Win32Constants.IMAGE_D ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException

Specified cast is not valid.
At line:2266 char:7
+         if (($PEInfo.DllCharacteristics -band $Win32Constants.IMAGE_D ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException
```

In spite of the error, the file is copied.

**Comment by HarmJ0y** [comment]
Thanks for the information. We will be doing a refactor of a chunk of PowerSploit code at some point after BlackHat and we will dive into this cast issue then.

**Comment by leechristensen** [comment]
Until/if this module is refactored, consider using PowerForensics to pull the file as it uses the same technique (https://github.com/Invoke-IR/PowerForensics)

**Comment by FuzzySecurity** [comment]
@okazymyrov can you please have a look at the change I pushed to the dev branch:
https://github.com/PowerShellMafia/PowerSploit/commit/bd6fe64316afe293d6b4cdf095ed3cfb64b6ab25

This should resolve the issue!

**Comment by okazymyrov** [comment]
@FuzzySecurity the changes work on Windows 10.0.14393.

**Comment by FuzzySecurity** [comment]
@okazymyrov ok cool! For now it's in Dev but in a week or two the change should have been pushed to master.
