### ISSUE TITLE
Get-VaultCredential fails on Windows 10 & Windows 7

### ISSUE THREAD

**Issue by byt3bl33d3r** [PowerShellMafia/PowerSploit#163]
Hey all,

I noticed that Get-VaultCredential throws an error and fails to decrypt web credentials when run on Windows 10 or Windows 7:
# Windows 10

![vault_creds](https://cloud.githubusercontent.com/assets/5151193/16507774/df75180a-3ee9-11e6-9fac-8fd85712a213.png)

Screenshot of the creds in the credential manager:

![vault_pass](https://cloud.githubusercontent.com/assets/5151193/16507815/170c242a-3eea-11e6-88f6-8adfe68b584a.png)
# Windows 7

On Windows 7, no errors are thrown and there's no output:

![vault](https://cloud.githubusercontent.com/assets/5151193/16507850/6bf03eae-3eea-11e6-8bed-0b0bfd9bc0fb.png)

Screenshot of the creds in the credential manager:

![vault_pass2](https://cloud.githubusercontent.com/assets/5151193/16507857/7c13b856-3eea-11e6-9d1d-d7578eead64e.png)

Tested this in both Powershell x86 & x64 with full Admin privs. 
Let me know if you need any more information!

Cheers

**Comment by byt3bl33d3r** [comment]
Gahh, ignore the commit spam, that was me being stupid

**Comment by HarmJ0y** [comment]
Thanks for the information. We will be doing a refactor of a chunk of PowerSploit code at some point after BlackHat and we will dive into this cast issue then.

**Comment by 0x6d6178** [comment]
Any update on this issue? Unfortunately, still not working for Windows 7 (did not verify Windows 10). Any pointers to info that we could use to fix it and submit a PR?

**Comment by leechristensen** [comment]
Possible alternatives: 
 - Mimikatz's vault's module
 - Manually copy the directories containing the vault data and the user's DPAPI blob, migrate them to a machine you control, and then viewing them on your own machine.

**Comment by FuzzySecurity** [comment]
This is working now! There was a problem here with the OS version check. Previously:
```
$OSMajor -ge 6 -and $OSMinor -ge 2
```
This doesn't work because version 10.0 for example fails this check. Changed to:
```
$OSVersion -ge '6.2'
```
Dev branch commit here:
https://github.com/PowerShellMafia/PowerSploit/commit/1950a169e3a979108fe3fe8df2306ce78bae6a75

Closing this issue for now!
