### ISSUE TITLE
Get-NetGroupMember - Enumeration error

### ISSUE THREAD

**Issue by sa7mon** [PowerShellMafia/PowerSploit#164]
I attempted to enumerate all users in all domain groups with the following command:
`Get-NetGroup | Get-NetGroupMember | Export-Csv members.csv` on a large domain and got the following error:

> An error occured while enumerating through a collection: An operations error occured.
> At C:...\Documents\WindowsPowerShell\Modules\Recon\PowerView.ps1:4670 char:17
> -               <<<< $GoupSearcher.FindAll() | ForEach-Object {
> - CategoryInfo   : InvalidOperation: (System.Director..sultsEnumerator:ResultsEnumerator) [], RuntimeException
> - FullyQualifiedErrorId : BadEnumeration

I tried outputting the results of `Get-NetGroup` to file, then piping the file into `Get-NetGroupMember`, but it still had the same errors. The script seems to keep running through the error a number of times, but then eventually stops running with no further errors. Are the groups just too big for the script to handle?

**Comment by sa7mon** [comment]
Version running: 262a260

**Comment by HarmJ0y** [comment]
I'm unable to reproduce in my lab. Can you provide the -Verbose flag to Get-NetGroupMember and let us know if there's any additional output/information?

And can you confirm whether you're able to do `net group GROUPNAME /domain` from the command line?

**Comment by HarmJ0y** [comment]
Closing due to lack of response.
