### ISSUE TITLE
Persistence removal script doesn't remove

### ISSUE THREAD

**Issue by pyrohaz4good** [PowerShellMafia/PowerSploit#165]
Hello,

When using the persistence (any of the options), the script block is still triggering every time powershell is run. This is even though the scheduled task is gone and the registry key is gone. Any ideas on how to fix this? My test machines keep connecting to my server, which is obviously not the point...

**Comment by pyrohaz4good** [comment]
I think the problem here is that the payload is being added to the profile.ps1, which gets executed every time powershell is invoked. Perhaps the profile file should be optionally removed in the removal scripts.

**Comment by FuzzySecurity** [comment]
Hola, I fixed this issue in Dev, the removal script should have an line now to clean up the profile and leave any legitimate content in tact. I think this module probably needs a bit of work and I may rewrite it after BH/DefCon but this should do as a temporary fix.

See:
https://github.com/PowerShellMafia/PowerSploit/commit/d5c0abc9facfc4d851613af7e5872d533250d683
