### ISSUE TITLE
Request-SPNTicket doesn't handle arrays of SPN

### ISSUE THREAD

**Issue by Meatballs1** [PowerShellMafia/PowerSploit#167]
A user can have a number of SPN, so  when using `get-netuser -spn | request-spnticket` the object maybe be an array passed to:

`New-Object System.IdentityModel.Tokens.KerberosRequestorSecurityToken -ArgumentList $SPN` rather than a single string...

**Comment by Meatballs1** [comment]
```
	if ($SPN -is [system.array]) {
		$SPN | ForEach-Object { 
        		Write-Verbose "Requesting ticket for: $_"
        		New-Object System.IdentityModel.Tokens.KerberosRequestorSecurityToken -ArgumentList $_
		}
	} else 
	{
        	Write-Verbose "Requesting ticket for: $SPN"
        	New-Object System.IdentityModel.Tokens.KerberosRequestorSecurityToken -ArgumentList $SPN
	}
```

Was my ghetto fix

**Comment by HarmJ0y** [comment]
This should now be fixed in the dev branch. If the issue persists, feel free to open this one back up!
