### ISSUE TITLE
domain share sometimes differs from domain controller shares

### ISSUE THREAD

**Issue by johnmccash** [PowerShellMafia/PowerSploit#169]
I just ran into a situation where a password was not properly detected by Get-GPPPassword. In this instance, the shares for individual DCs, such as:
\\<dc name>\sysvol\<domain>\Policies\<GUID>\Machine\Preferences\Groups
differed from the equivalent share for the domain as a whole, such as:
\\<domain>\sysvol\<domain>\Policies\<GUID>\Machine\Preferences\Groups
and it's the latter share that Get-GPPPassword is interrogating to identify possible insecurely stored passwords. I'd suggest that Get-GPPPassword be modified to optionally interrogate the shares for all DCs, or at least to check the domain share and one DC share. I'm not sure whether this is typical behavior, or if it's indicative of a broken config, but it's obviously possible. It appears that in my case, the shares for each of the individual DCs were the same, but it's not clear that they necessarily have to be.

**Comment by johnmccash** [comment]
Oops. That wasn't what the problem was. Still looking for the exact cause, but I was comparing 2 different GUIDS. The password was definitely present, and wasn't detected, but I'm still not sure why.

**Comment by HarmJ0y** [comment]
As far as I understand it, SYSVOL is replicated between all domain controllers within a particular domain through [FRS](https://en.wikipedia.org/wiki/File_Replication_Service) or DFS. Since this is the normal behavior, we're going to keep it at one SYSVOL access.

**Comment by johnmccash** [comment]
Did you look at https://github.com/PowerShellMafia/PowerSploit/issues/170 ? I closed this one and opened that one after figuring out that I'd misstated the problem. I just checked, and there's no update on it though.
