### ISSUE TITLE
Get-GPPPassword does (sometimes?) incorrect XML extraction on ScheduledTasks.xml

### ISSUE THREAD

**Issue by johnmccash** [PowerShellMafia/PowerSploit#170]
I just ran into a situation where a password was not properly detected by Get-GPPPassword. In this instance, it appears that the xml in the ScheduledTasks.xml file was different than what the tool is expecting to extract from. In the code, it says:

```
                'Scheduledtasks.xml' {
                    $Cpassword += , $Xml | Select-Xml "/ScheduledTasks/Task/Properties/@cpassword" | Select-Object -Expand Node | ForEach-Object {$_.Value}
                    $UserName += , $Xml | Select-Xml "/ScheduledTasks/Task/Properties/@runAs" | Select-Object -Expand Node | ForEach-Object {$_.Value}
                    $Changed += , $Xml | Select-Xml "/ScheduledTasks/Task/@changed" | Select-Object -Expand Node | ForEach-Object {$_.Value}
                }
```

But what I see in the xml file is:
                    /ScheduledTasks/TaskV2/Properties/@cpassword
                    /ScheduledTasks/TaskV2/Properties/@runAs
                    /ScheduledTasks/TaskV2/@changed

The difference is "/Task/" vs. "/TaskV2/" I assume this to be a version issue, . It looks like there needs to be a change to enable parsing of this alternate format.

Thanks

**Comment by HarmJ0y** [comment]
We're currently working on a fix for this- after testing we will try to get it into the dev branch.

**Comment by johnmccash** [comment]
NTAC:3NS-20
Thanks very much. I'm surprised it took so long to take a look at this.
                John

**Comment by mattifestation** [comment]
I suppose you get what you pay for, eh?

**Comment by johnmccash** [comment]
NTAC:3NS-20
Fair point.
                John

**Comment by HarmJ0y** [comment]
This should be fixed on the dev branch with https://github.com/PowerShellMafia/PowerSploit/commit/5500a7e1311662a8e88d1361ef0d8ab86f8f35b5 . I'm going to close this for now but feel free to reopen if the fix doesn't work.
