### ISSUE TITLE
Explanations or Improvements?

### ISSUE THREAD

**Issue by AresS31** [PowerShellMafia/PowerSploit#171]
Hi,

I have been playing with PowerSploit for a while now and I must admit that it is a really awesome framework. However, I can't make the scripts work on a Domain which I am not part of. 
Let's say, I have got valid domain user credentials and the domain name. I would like from there to query the DC for the user list (using get-netusers) or computers for instance. This won't be possible isn'it? 
I have searched since a week and had a look at the full help for plenty of methods. But I could not make the scripts work when I am not part of a Domain. Am I just missing something out or if this feature not implemented in which case I reckon this would be a **GREAT** improvement to make to PowerSploit to make it a bit like enum4linux when we can use a NULL session or credentials and give the Domain target to query.

Kind regards,
Alex

**Comment by leechristensen** [comment]
Use the "runas /netonly" command to start PowerShell with your domain
credentials.  See https://www.sixdub.net/?p=579 for more details.

**Comment by AresS31** [comment]
I have tried that command line:
`runas.exe /netonly /user:DOMAIN/myUser "powershell.exe -exec bypass" `
And it is still not working I followed the tutorial, my testing lab is properly set, any solution?

**Comment by jacobgarner** [comment]
Your slash between domain and username is backwards / versus \

**Comment by AresS31** [comment]
Sorry, I just mispelled it. I used the good slash type for my tests. :)
I really want to make this work! I am on an internal engagement next week and I would like to have a play with PowerSploit on the "real world".

**Comment by jacobgarner** [comment]
The runas method described above worked for me in a previous engagement.
Perhaps you can post your actual command with redacted password.

**Comment by AresS31** [comment]
It might be misconfiguration of my DOMAIN Lab, I will test that next week anyway. Thanks for your help @jacobgarner
