### ISSUE TITLE
Get-NetLocalGroup -ComputerName

### ISSUE THREAD

**Issue by boyjaew** [PowerShellMafia/PowerSploit#175]
Probably something simple I am overlooking, but when running Get-NetLocalGroup -ComputerName _name_ or seemingly anything that depends on it I get the following error:

WARNING: [!] Error: Error while invoking GetType. Could not find member.

**Comment by hannestrunde** [comment]
I had the same problem and stumbled upon this thread on stackoverflow:
http://stackoverflow.com/questions/31949541/print-local-group-members-in-powershell-5-0

This seems to be a problem with PowerShell version 5.

I could solve this problem through replacing the following lines in the PowerView.ps1:

```
6287		$_.GetType().InvokeMember(...) ------> $_.GetType.Invoke().InvokeMember(...)
6305		$_.GetType().InvokeMember(...) ------> $_.GetType.Invoke().InvokeMember(...)
6309		$_.GetType().InvokeMember(...) ------> $_.GetType.Invoke().InvokeMember(...)
6312		$_.GetType().InvokeMember(...) ------> $_.GetType.Invoke().InvokeMember(...)
6320		$_.GetType().InvokeMember(...) ------> $_.GetType.Invoke().InvokeMember(...)
```

**Comment by boyjaew** [comment]
Solid Gold! Thank you.
