### ISSUE TITLE
Invoke-EnumerateLocalAdmin not working with groupnames other than "Administrators"

### ISSUE THREAD

**Issue by hannestrunde** [PowerShellMafia/PowerSploit#176]
When running Invoke-EnumerateLocalAdmin the script only enumerates groups named "Administrators". However, on a German Windows this group is named "Administratoren".

To get it working I just had to change Line 6231 in PowerView.ps1 in the master branch from `$GroupName = 'Administrators',` to `$GroupName,`. Then the `begin` section of the script (lines 6240 to 6247) will do it's magic and get the correct group name.

I wanted to initiate a pull request when i saw that the whole `begin` section was removed from the code in the dev branch (lines 6626 to 6633):
https://github.com/PowerShellMafia/PowerSploit/commit/b4891eb371c83c0eef7cc3d4485b3a7066c9641e

I tried the Invoke-EnumerateLocalAdmin script from the dev branch on my German Windows 7 machine because I thought maybe I was missing something but it obviously tried to enumerate the group "Administrators" again and that of course failed with:

WARNING: [!] Error: Exception calling "Invoke" with "2" argument(s): "Der Gruppenname konnte nicht gefunden werden.

which translates to:

WARNING: [!] Error: Exception calling "Invoke" with "2" argument(s): "The group name could not be found.

Is there a specific reason why the `begin` section to fetch the group name based on the security identifier was removed?

**Comment by FuzzySecurity** [comment]
A possible solution for this is using System.Security.Principal.WellKnownSidType

```
PS C:\Users\b33f> $SecurityIdentifier = New-Object System.Security.Principal.SecurityIdentifier([System.Security.Principal.WellKnownSidType]::BuiltinAdministratorsSid,$null)
PS C:\Users\b33f> $SecurityIdentifier

                                     BinaryLength AccountDomainSid                                  Value
                                     ------------ ----------------                                  -----
                                               16                                                   S-1-5-32-544
PS C:\Users\b33f> ($SecurityIdentifier.Translate([System.Security.Principal.NTAccount]).Value -split "\\")[-1]
Administrators
```

I think that should be a region independent way of getting the admin group name (or any other group for that matter).

**Comment by FuzzySecurity** [comment]
Hola, the Group Name can be set when the function is called which would solve your problem. However I added a check in the function to enumerate the admin groupname if it is using the default "Administrators" string.

https://github.com/PowerShellMafia/PowerSploit/commit/7a3e16ace550fb335182960576aab236a0a00219

Let me know if that works, closing for now.

**Comment by FuzzySecurity** [comment]
I had a typo in my commit, but fixed here:
https://github.com/PowerShellMafia/PowerSploit/commit/b038f09ceba0ccbdff946a802e4529427cfaee5e

**Comment by ClementNotin** [comment]
This fix is interesting @FuzzySecurity. However if I understand well, the translation from the SID to the string name is done on the current machine, not on the target. So if I'm using an English Windows, and targeting a German one, the SID won't be correct for the target system. Is it correct?
I tried a different approach for Get-NetLocalGroupMember (which is used by Find-DomainLocalGroupMember) in https://github.com/PowerShellMafia/PowerSploit/pull/252, tell me your opinion!
