### ISSUE TITLE
Small spelling errors in PowerSploit/Privesc/PowerUp.ps1:1191 and :2267

### ISSUE THREAD

**Issue by martijnsprengers** [PowerShellMafia/PowerSploit#179]
Line 2191 of PowerSploit/Privesc/PowerUp.ps1 contains a small spelling error: 
`ConvertTo-HTML -Head $Header -Body "<H2> User In Local Group With Adminisrtative Privileges</H2>" | Out-File -Append $HtmlReportFile`

Adminisrtative -> Administrative

Line 2267 of PowerSploit/Privesc/PowerUp.ps1 contains a small spelling error:
`$Results | ConvertTo-HTML -Head $Header -Body "<H2>Vulnerabl Schasks</H2>" | Out-File -Append $HtmlReportFile`

Vulnerabl Schasks -> Vulnerable Schtasks

**Comment by HarmJ0y** [comment]
Thanks, these will be fixed shortly in the refactor that will be pushed in the next few days.
