### ISSUE TITLE
Error when running Invoke-UserHunter

### ISSUE THREAD

**Issue by jlang7** [PowerShellMafia/PowerSploit#181]
Invoke-UserHunter -Stealth -StealthSource 'DC' -UserFile {input} | out-file -encoding ASCII {output}

Error Message

`<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="warning">Error: An error occurred while enumerating through a collection: More data is available._x000D__x000A_.</S></Objs>`

**Comment by HarmJ0y** [comment]
Interesting, haven't run into this before. The only applicable Google result I could find for that error [is here](https://powershell.org/forums/topic/searching-ad-badenumeration-more-data-is-available/). So there's a possibility that the search itself took too long on the DC and everything errored out.

For the refactor we're currently executing, I'll look into making ServerTimeLimit a universal option that can be set for any query function for cases like this.
