### ISSUE TITLE
Incomplete CSV output when running Invoke-EnumerateLocalAdmin 

### ISSUE THREAD

**Issue by s3c** [PowerShellMafia/PowerSploit#183]
I currently have a problem where Invoke-EnumerateLocalAdmin sometimes only return a single admin on each workstation when using CSV output. This doesn't always happen however, as the same script works on a different host on another domain in the same forest. On this second host I get all the admins for every host. This was tested using the dev branch on commit 8c9c7c8.

An example command below:

Invoke-EnumerateLocalAdmin -OutFile localadmin.txt -Threads 32

**Comment by HarmJ0y** [comment]
I played with this but wasn't able to recreate, so without additional information there's not a way to easily track it down.
