### ISSUE TITLE
Invoke-UserEventHunter appears to be missing

### ISSUE THREAD

**Issue by mandreko** [PowerShellMafia/PowerSploit#184]
I tried using the UserEventHunter functionality outlined in the PowerView readme (https://github.com/PowerShellMafia/PowerSploit/blob/master/Recon/README.md). It appears that the function is missing from the repository, or has been updated and the documentation is no longer accurate. 

To test, I imported PowerSploit into a PowerShell instance, and tried running Invoke-UserEventHunter. It was stating that it couldn't find the function. To make sure PowerSploit actually loaded properly, I called another function, Invoke-CheckLocalAdminAccess. The output can be seen below:

```
PS C:\Users\user> Import-Module .\Desktop\PowerSploit\PowerSploit.psm1
PS C:\Users\user> Invoke-UserEventHunter
The term 'Invoke-UserEventHunter' is not recognized as the name of a cmdlet, function, script file, or operable program
. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:23
+ Invoke-UserEventHunter <<<<
    + CategoryInfo          : ObjectNotFound: (Invoke-UserEventHunter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\user> Invoke-CheckLocalAdminAccess
False
```

After that, I tried searching for the string in the source repository, and I can't find it anywhere:

```
root@kali:~/PowerSploit# grep -irl "UserEventHunter" *
Recon/README.md
```

**Comment by mandreko** [comment]
Good Catch. It should be updated in the README.md file for sure.

**Comment by HarmJ0y** [comment]
We are in the middle of a PowerSploit refactor- additional functions are being renamed, and documentation will be corrected once the new version is released.
