### ISSUE TITLE
Get-Timedscreenshot is incompatible with Windows running in VMWare Fusion(retina screen)

### ISSUE THREAD

**Issue by CaledoniaProject** [PowerShellMafia/PowerSploit#186]
Here's the screenshot I take with Get-TimedScreenshoot

![10-20-2016-14-46-34](https://cloud.githubusercontent.com/assets/1357701/19549345/637f4cd0-96d6-11e6-90bf-18381d1304a2.png)

I'm running VMWare Fusion 8.5 with Retina Mac
The guest machine is running Windows 8.1 

It looks like only a quarter of the screen is recorded ... 
Might be related to retina screen, not a big problem though

**Comment by CaledoniaProject** [comment]
The left cmd windows is vertically maximized.

**Comment by HarmJ0y** [comment]
We haven't run into this, but will try to recreate.

**Comment by okazymyrov** [comment]
@CaledoniaProject have you tried the dev version? It contains some changes in comparison to the master script. 

If you get an error look at https://github.com/PowerShellMafia/PowerSploit/pull/220 for the fix.

**Comment by CaledoniaProject** [comment]
Yes, it's fixed in dev branch

**Comment by FuzzySecurity** [comment]
Close as fixed in dev.
