### ISSUE TITLE
PowerView - GetDomainSID does not take -Credential parameter

### ISSUE THREAD

**Issue by Meatballs1** [PowerShellMafia/PowerSploit#188]
Should pass to Get-NetDomain and Get-NetComputer subfunctions.

**Comment by HarmJ0y** [comment]
Yep. We're starting a PowerSploit refactor, and I'm *most* of the way through PowerView now (about 20% left). One of the big changes was parameter standardization and -Credential support, which will be in the version released (hopefully soonish).

**Comment by HarmJ0y** [comment]
This should be fixed in the dev branch as of https://github.com/PowerShellMafia/PowerSploit/commit/7c32bf69f334b7c15c644cdb41188bdfe1a0b0e8 , if it's still an issue feel free to reopen.
