### ISSUE TITLE
Windows 10 ENT  1607 Build 14393.351

### ISSUE THREAD

**Issue by yannickwe87** [PowerShellMafia/PowerSploit#190]
All,

Currently having issues that powersploit Invoke-Mimikatz fails to run on aforementioned build/version. I receive this error:

mimikatz(powershell) # sekurlsa::logonpasswords
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

The official source code from https://github.com/gentilkiwi/mimikatz works like a charm (.exe)

**Comment by mattifestation** [comment]
Updated in the dev branch. Please validate that it works for you.
