### ISSUE TITLE
Invoke-ReflectivePEInjection c# exe

### ISSUE THREAD

**Issue by homeboyconsequences** [PowerShellMafia/PowerSploit#196]
Thanks for the amazing script, i'm having this issue when trying to inject a c# vs2015 compiled exe

APPCRASH
  Application Name:	powershell.exe
  Application Version:	6.2.9200.16398
  Application Timestamp:	50338287
  Fault Module Name:	clr.dll
  Fault Module Version:	4.6.1076.0
  Fault Module Timestamp:	56d7a0ff
  Exception Code:	c0000005
  Exception Offset:	0011a360
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1046
  Additional Information 1:	3387
  Additional Information 2:	3387838cbcc82de219e3468c99f75704
  Additional Information 3:	f1f6
  Additional Information 4:	f1f67c6374886f9f2e1b6803a0e3c517

**Comment by HarmJ0y** [comment]
Invoke-ReflectivePEInjection is used for unmanaged (C/C++) code. For managed (C#) code check out [Out-CompressedDll](https://github.com/PowerShellMafia/PowerSploit/blob/master/ScriptModification/Out-CompressedDll.ps1).
