### ISSUE TITLE
Get-ModifiableServiceFile false positives due to arguments

### ISSUE THREAD

**Issue by Quiark** [PowerShellMafia/PowerSploit#223]
I'm getting the following results, for example:

```
Path                            : "C:\Program Files (x86)\Google\Update\GoogleUpdate.exe" /svc
ModifiableFile                  : C:\

ServiceName                     : Steam Client Service
Path                            : "C:\Program Files (x86)\Common Files\Steam\SteamService.exe" /RunAsService
```

But the files or folders are not writeable. The reason they are listed is that `Get-ModifiablePath` will receive the path including the argument (such as `/svc`) and then treat this as two path items. The second one is writeable so it reports the result even though the main path is not.

**Comment by FuzzySecurity** [comment]
I am unable to reproduce this issue, can you please check out the latest version in the Dev branch to test. I tried to implement your use case, see the screenshot below:

![image](https://user-images.githubusercontent.com/10997340/28291770-c3bfb156-6b43-11e7-99f6-f2cd4b7a76cc.png)

**Comment by Quiark** [comment]
It seems ok with dev branch code. But I also changed permissions on `c:\` so that may have fixed it...

**Comment by FuzzySecurity** [comment]
Cool, I wanted to make sure. If it turns out there is still some issue here, please reopen the ticket!
