### ISSUE TITLE
Invoke-UserHunter -- blank output

### ISSUE THREAD

**Issue by okiwoki** [PowerShellMafia/PowerSploit#224]
For some reason, Invoke-UserHunter on recon/PowerView.ps1 is giving me a blank output no matter what parameters I'm using. I'm making sure a domain admin user is currently logged into another system on my test domain, and I have also tried other users to no avail.

Is anyone else experiencing the same isue?

Output:

PS C:\Users\pam\Desktop> Invoke-UserHunter -CheckAccess
PS C:\Users\pam\Desktop> Invoke-UserHunter -SearchForest
PS C:\Users\pam\Desktop> Invoke-UserHunter
PS C:\Users\pam\Desktop> Invoke-UserHunter
PS C:\Users\pam\Desktop> Invoke-UserHunter
PS C:\Users\pam\Desktop> Invoke-UserHunter
PS C:\Users\pam\Desktop> Invoke-UserHunter
PS C:\Users\pam\Desktop> Invoke-UserHunter -StopOnSuccess
PS C:\Users\pam\Desktop> Invoke-UserHunter -SearchForest
PS C:\Users\pam\Desktop> Invoke-UserHunter -GroupName "helpdesk"
PS C:\Users\pam\Desktop> Invoke-UserHunter -GroupName "helpdesk"
PS C:\Users\pam\Desktop> Invoke-UserHunter -GroupName "helpdesk"
PS C:\Users\pam\Desktop> Invoke-UserHunter -UserName scarlett
PS C:\Users\pam\Desktop>

**Comment by HarmJ0y** [comment]
By default it searches for/filters for "Domain Admins" or the group you specified, but depending on various factors it just might not have found the targets. You can use **-ShowAll** to show ALL results, as well as **-Verbose** to get more detailed output to see what's going on.
