### ISSUE TITLE
Feature Request: use local cache for GPP search

### ISSUE THREAD

**Issue by ilmarh** [PowerShellMafia/PowerSploit#229]
I could be nice to have Get-GPPPassword.ps1 seek local GPP cache (%windir%\System32\GroupPolicy\DataStore) for stored prefs with encrypted local admin passwords.

**Comment by HarmJ0y** [comment]
[Privesc/PowerUp.ps1](https://github.com/PowerShellMafia/PowerSploit/blob/dev/Privesc/PowerUp.ps1) currently does do this with [Get-CachedGPPPassword](https://github.com/PowerShellMafia/PowerSploit/blob/d12e1516f872ff32098677ac70bec901136365db/Privesc/PowerUp.ps1#L4312-L4516).
