### ISSUE TITLE
Get-GPPPassword.ps1

### ISSUE THREAD

**Issue by benpturner** [PowerShellMafia/PowerSploit#247]
$AesObject = New-Object System.Security.Cryptography.AesCryptoServiceProvider

This doesnt work on Powershell v2 on windows 7 by default. 

![gpp](https://user-images.githubusercontent.com/2518196/27836874-440854a0-60d9-11e7-95f8-4dae9fe71c6b.png)

**Comment by HarmJ0y** [comment]
I'm going to need more details/recreation steps, as I was able to confirm that the object is created for a PS Version 2 Win7 system-

![image](https://user-images.githubusercontent.com/5504523/27840574-fb50ad22-60ae-11e7-8e48-4530e40591ed.png)

**Comment by secabstraction** [comment]
# First see if it has a FIPS algorithm
        $CryptoServiceProviderType = "System.Security.Cryptography.${Algorithm}CryptoServiceProvider" -as [Type]
        if ($CryptoServiceProviderType) { $CryptoProvider = New-Object $CryptoServiceProviderType }
        else {
            # Check if the type is supported in the current system
            $CryptographyType = "System.Security.Cryptography.${Algorithm}" -as [Type]
            if ($CryptographyType) {
                if ($Algorithm -eq 'MACTripleDES') { $CryptoProvider = New-Object $CryptographyType }
                else { $CryptoProvider = $CryptographyType::Create() }
            }

xoxo

**Comment by secabstraction** [comment]
```powershell
# First see if it has a FIPS algorithm
$CryptoServiceProviderType = "System.Security.Cryptography.${Algorithm}CryptoServiceProvider" -as [Type]
if ($CryptoServiceProviderType) { $CryptoProvider = New-Object $CryptoServiceProviderType }
else {
    # Check if the type is supported in the current system
    $CryptographyType = "System.Security.Cryptography.${Algorithm}" -as [Type]
    if ($CryptographyType) {
        if ($Algorithm -eq 'MACTripleDES') { $CryptoProvider = New-Object $CryptographyType }
        else { $CryptoProvider = $CryptographyType::Create() }
    }
}
```
xoxo

**Comment by benpturner** [comment]
Could be a random one: 
![gpp2](https://user-images.githubusercontent.com/2518196/27842872-c4263568-6105-11e7-999b-de39481959ca.png)

**Comment by benpturner** [comment]
There are some GPO restrictions applied but nothing I can see that would easily prevent this. It works on other Windows 7 installs but not sure if anything has been added or removed.

**Comment by benpturner** [comment]
Even more interesting, it works on 32bit powershell - 
![gpp3](https://user-images.githubusercontent.com/2518196/27843011-41aea38e-6107-11e7-9c01-e7e7f367ca5f.png)

**Comment by FuzzySecurity** [comment]
It works fine for me on x64 Win7, can you please check "System.dll" is loaded ¯\_(ツ)_/¯
```
[AppDomain]::CurrentDomain.GetAssemblies()|Where {$_.Location -match '\\System\\'}
```

**Comment by benpturner** [comment]
It looks like system.core.dll isn't loaded which runs this bit of the code. 

Do you have any idea why this wouldn't be loaded by default.

**Comment by FuzzySecurity** [comment]
Tyr this:
```
[System.Reflection.Assembly]::LoadWithPartialName("System")
```
And then:
```
New-Object System.Security.Cryptography.AesCryptoServiceProvider
```

Not sure what the reason would be to be honest, but I have a vague memory of encountering this at some point.

**Comment by FuzzySecurity** [comment]
Or maybe:
```
[System.Reflection.Assembly]::LoadWithPartialName("System.Core")
```
As the case may be.

**Comment by secabstraction** [comment]
Did you bother trying the snippet I posted?
________________________________

**Comment by benpturner** [comment]
Yeh sorry, just errors at the else statement.

**Comment by secabstraction** [comment]
Maybe FIPS?

https://www.howtogeek.com/245859/why-you-shouldnt-enable-fips-compliant-encryption-on-windows/
________________________________

**Comment by FuzzySecurity** [comment]
@benpturner was there a resolution for this issue?

**Comment by benpturner** [comment]
Yes, basically if we do a test to see if the System.Core is loaded.
 This could be added
[System.Reflection.Assembly]::LoadWithPartialName("System.Core")

**Comment by benpturner** [comment]
Not sure if you want to close it or add a quick check before decrypting the value

**Comment by FuzzySecurity** [comment]
@benpturner so if you do this before running the script it works fine?
```powershell
[System.Reflection.Assembly]::LoadWithPartialName("System.Core") |Out-Null
```
If so, it's probably wise to just add that in for edge-cases.

**Comment by benpturner** [comment]
yeah for sure

**Comment by FuzzySecurity** [comment]
Cool, I pushed the change to Dev https://github.com/PowerShellMafia/PowerSploit/commit/41cad0ee9fa8a18a77d68b696c2cc24d14e95352

**Comment by benpturner** [comment]
Thanks @FuzzySecurity
