### ISSUE TITLE
Question When Use it?

### ISSUE THREAD

**Issue by sat3007** [PowerShellMafia/PowerSploit#251]
hi first thanks for This Good Framework.
we think like that : 

We Go to a network (With Enter to Wireless) and in this Network We Have some Windows OS
One Windows Server 2008
and some Windows 7

and with Sniffing Network We get the SMB Hash and with cracking hash we get the password.

and now we have user/pass. 
now my question is there.

we First Login to Domain with this user/pass Or we not need to login to domain (and when We enter To Network With out Login to domain We Can Use the PowerSploit) ???
   if we need To Login 
           How We login To domain?
Like Always? (we Go to ((Control Panel -> System and Security -> system - > Change Settings -> Change)) And there we set domain name and enter User/pass  ) Or We Need do something Else ?

Thank you so much : ).
Good Luck.
sorry for bad en.

**Comment by HarmJ0y** [comment]
Hello,

Thanks for the question. There are many ways to proceed based on how you have described your situation. I would recommend taking a look at the following resources which might help provide some guidance on inspiration on what to do next:

https://www.sixdub.net/?p=579
http://www.harmj0y.net/blog/tag/powerview/
http://www.harmj0y.net/blog/powershell/make-powerview-great-again/

In general, you do not need to add your computer to the domain to be able to enumerate AD. If the hash is a local admin, I would recommend getting a shell on a domain-joined system (plenty of resources exist for how to do this). If not, I would recommend you look at the posts above for how to enumerate AD from a non-domain joined Windows system, or look at the CrackMapExec project (https://github.com/byt3bl33d3r/CrackMapExec) for how to do this from a Linux system with network access.
