### ISSUE TITLE
Is Find-DomainShare removed from PowerSpolit?

### ISSUE THREAD

**Issue by CaledoniaProject** [PowerShellMafia/PowerSploit#283]
I see the documentation about [Find-DomainShare](http://powersploit.readthedocs.io/en/latest/Recon/Find-DomainShare/) here, but it's no longer present in the repository. 

Did I miss something?

**Comment by gabemarshall** [comment]
Make sure you look in the [dev branch](https://github.com/PowerShellMafia/PowerSploit/blob/dev/Recon/PowerView.ps1). I believe the master branch still has it labeled as Invoke-ShareFinder.

**Comment by CaledoniaProject** [comment]
Thanks
