### ISSUE TITLE
Is Get-DomainUser/Get-DomainComputer -TrustedToAuth removed from PowerSpolit? 

### ISSUE THREAD

**Issue by Dliv3** [PowerShellMafia/PowerSploit#303]
How can i find users/computers with constrained delegation?

**Comment by leechristensen** [comment]
Use the "dev" branch: https://github.com/PowerShellMafia/PowerSploit/blob/dev/Recon/PowerView.ps1#L4906

**Comment by Dliv3** [comment]
ok thank you
