### ISSUE TITLE
Installation Using PS-Get:

### ISSUE THREAD

**Issue by 0x0mar** [PowerShellMafia/PowerSploit#67]
Installation Using PS-Get:
1. (new-object Net.WebClient).DownloadString("http://psget.net/GetPsGet.ps1") | iex
2. Set-ExecutionPolicy RemoteSigned
3. install-module PsUrl
4. install-module -ModuleUrl https://github.com/mattifestation/PowerSploit/archive/master.zip
5. Import-Module PowerSploit
6. Get-Command -Module PowerSploit 
7. Done!

**Comment by PowerShellMafia** [comment]
Thanks for the info!
