### ISSUE TITLE
Out-EncryptedScript.ps1 - Issues with ASCII Encoding

### ISSUE THREAD

**Issue by aconite33** [PowerShellMafia/PowerSploit#80]
While testing the latest version of Out-EncryptedScript, we noticed that you modified the latest version to take in the script in the form of `Text.Encoding::ASCII.GetBytes`. This will mangle the script when it is decrypted on the other side.
Using your original code of just grabbing the script in Byte format instead of ASCII will result in the original script executing properly.
I tested this with Invoke-Mimikatz.ps1
Changing line #83 in Out-EncryptedScript.ps1 back to:
`[Byte[]] $scriptBytes = Get-Content -Encoding byte -Path $ScriptPath`
will correct this problem.

**Comment by PowerShellMafia** [comment]
This seems to have done the trick for both unicode and ascii encoded scripts. Thanks for your patience on this one. PowerSploit is back under active dev now! :)

Cheers,
Matt
