### ISSUE TITLE
Issue with Invoke-DllInjection.ps1

### ISSUE THREAD

**Issue by 3gstudent** [PowerShellMafia/PowerSploit#85]
https://github.com/PowerShellMafia/PowerSploit/blob/master/CodeExecution/Invoke-DllInjection.ps1

`$Proc = Get-Process notepad`
`Invoke-DllInjection -ProcessId $Proc.Id -Dll DemoDLL.dll`

When I use the above command to inject DemoDLL.dll into the running process notepad.exe on Windows8 x64
it occurs
`PE file was not compiled for x86.`

I think Line284 should be
`if ($Architecture -eq 'X86')`
and it will solve the probmlem:)

**Comment by PowerShellMafia** [comment]
In 64-bit Windows 8, that line shouldn't even execute. Run the following and tell me what you get:

```powershell
(Get-WmiObject Win32_OperatingSystem).OSArchitecture
```

If that returns '64-bit' then line 284 cannot execute.

For reference, the check in [line 284](https://github.com/PowerShellMafia/PowerSploit/blob/master/CodeExecution/Invoke-DllInjection.ps1#L284) is designed to throw an error if you're trying to inject a non 32-bit dll into a process on a 32-bit operating system. Your suggested change is illogical.

**Comment by PowerShellMafia** [comment]
I'm going to close but if you run into any issues, please open a new issue.
