### ISSUE TITLE
PowerUp: Remove Add-Type call for helper enum

### ISSUE THREAD

**Issue by PowerShellMafia** [PowerShellMafia/PowerSploit#86]
Consider replacing the C# helper enum [here](https://github.com/PowerShellMafia/PowerSploit/blob/dev/Privesc/PowerUp.ps1#L18-L40) with either reflection code or a pure PowerShell implementation of those immediate values.

**Comment by HarmJ0y** [comment]
Should be resolved with https://github.com/PowerShellMafia/PowerSploit/commit/0181ff0c096216b105569fea2cc08f2d166aa3cb

**Comment by PowerShellMafia** [comment]
Noice. I like it.
