### ISSUE TITLE
PowerView: Pester tests are leaving file artifacts behind

### ISSUE THREAD

**Issue by PowerShellMafia** [PowerShellMafia/PowerSploit#87]
The following file artifacts are created and not cleaned up in Recon.tests.ps1:

1. shares.txt
2. targets.txt
3. target_users.txt

By forgetting to remove these artifacts this could allow one of the PowerSploit contributors to inadvertently commit these artifacts - potentially leaking sensitive personal information.

**Comment by HarmJ0y** [comment]
This should be fixed with https://github.com/PowerShellMafia/PowerSploit/commit/a2353139966fa5747d37c8288f821ea841e947ce

**Comment by PowerShellMafia** [comment]
I'm no longer seeing those artifacts persist. Thanks.
