### ISSUE TITLE
PowerView: Do some Pester tests require a domain?

### ISSUE THREAD

**Issue by PowerShellMafia** [PowerShellMafia/PowerSploit#88]
The following Recon.tests.ps1 tests are failing due to the fact that my machine is not attached to a domain:

* Invoke-UserHunter
* Invoke-StealthUserHunter
* Invoke-ProcessHunter
* Invoke-ShareFinder
* Invoke-FileFinder
* Find-LocalAdminAccess
* Invoke-EnumerateLocalAdmin

```
Assert failed on "GetCurrentDomain" with "0" argument(s): "Current security context is not associated with an Active Directory domain or forest."
```

I realize that these functions are best used on a domain joined machine but for the purposes of Pester tests, is that what you intend to do?

These tests also assume that %userdnsdomain% is defined. It isn't defined on my non domain-joined machine.

**Comment by HarmJ0y** [comment]
This should (hopefully) be fixed with https://github.com/PowerShellMafia/PowerSploit/commit/5690b09027b53a5932e42399f6943e03fa32e549

**Comment by PowerShellMafia** [comment]
I'm no longer seeing the exceptions thrown related to needing to be on a domain.
