### ISSUE TITLE
PowerUp: Pester tests are leaving file artifacts behind

### ISSUE THREAD

**Issue by PowerShellMafia** [PowerShellMafia/PowerSploit#89]
The following file artifacts are created and not cleaned up in Privesc.tests.ps1:

* RANDOM_8_CHARS.RANDOM_3_CHARS.exe

By forgetting to remove these artifacts this could allow one of the PowerSploit contributors to inadvertently commit these artifacts.

**Comment by HarmJ0y** [comment]
This should be fixed with https://github.com/PowerShellMafia/PowerSploit/commit/e2993b63aaf09026a11dc3ba2f0ae4a364f27113

**Comment by PowerShellMafia** [comment]
That did the trick. Thanks
