### ISSUE TITLE
PowerUp: Pester tests don't check for admin rights

### ISSUE THREAD

**Issue by PowerShellMafia** [PowerShellMafia/PowerSploit#90]
Functions requiring admin rights should check for admin rights and throw accordingly if not present. That way, the reason a Pester test fails will be more obvious. Also, this way, tests designed to test specific behavior will actually check that behavior versus throwing exceptions for unintended reasons.

**Comment by HarmJ0y** [comment]
Should be fixed with https://github.com/PowerShellMafia/PowerSploit/commit/9ffc26af70ae089405a5c5e8df40ad557818c103

**Comment by PowerShellMafia** [comment]
Yep. Looks great. Thanks!
