### ISSUE TITLE
Invoke-WmiCommand doesn't work properly in PSv2

### ISSUE THREAD

**Issue by PowerShellMafia** [PowerShellMafia/PowerSploit#96]
One of the core pieces of functionality in Invoke-WmiCommand is that it returns a proper PowerShell object. I do this in memory by using the System.Management.Automation.PSSerializer class to perform object [de]serialization. This class doesn't exist in PSv2 however. I could reimplement the logic in Import/Export-CliXml but I think I'll opt to just use Import/Export-Clixml and temporarily drop the execution results to disk and clean things up accordingly.

**Comment by secabstraction** [comment]
$obj | ConvertTo-Csv | [Convert]::ToBase64String($_)

**Comment by PowerShellMafia** [comment]
That won't preserve objects though. That will just output the root properties to text in the form of a CSV.

**Comment by secabstraction** [comment]
no... just tested with this and it worked.
$obj | % { [Convert]::ToBase64String($OutputEncoding.GetBytes($_)) } | % { [Text.Encoding]::UTF8.GetString([Convert]::FromBase64string($_)) } | ConvertFrom-Csv

**Comment by PowerShellMafia** [comment]
Nope. No object properties here:

```powershell
ps -id $PID | % { [Convert]::ToBase64String($OutputEncoding.GetBytes($_)) } | % { [Text.Encoding]::UTF8.GetString([Convert]::FromBase64string($_)) } | ConvertFrom-Csv
```

**Comment by secabstraction** [comment]
lmao, that's exactly what I have stored in $obj. let me try a couple more times (i'm on a win7 w/PSv2)

**Comment by secabstraction** [comment]
That's my bad, I left out the converting to csv first in that gist. my $obj was actually:
```powershell
$obj = ps -Id $PID | ConvertTo-Csv
```

```powershell
ps -Id $PID | ConvertTo-Csv | % { [Convert]::ToBase64String($OutputEncoding.GetBytes($_)) } | % { $OutputEncoding.GetString([Convert]::FromBase64string($_)) } | ConvertFrom-Csv
```

**Comment by PowerShellMafia** [comment]
Sure but like I said, "That won't preserve objects though. That will just output the root properties to text in the form of a CSV." I want full object serialization - i.e. preserved embedded properties and type info. CliXml is the only way to achieve that.

**Comment by PowerShellMafia** [comment]
```powershell
$obj = ps -Id $PID | ConvertTo-Csv
$newobj = $obj | % { [Convert]::ToBase64String($OutputEncoding.GetBytes($_)) } | % { $OutputEncoding.GetString([Convert]::FromBase64string($_)) } | ConvertFrom-Csv

# This won't return the loaded modules when imported as a csv
$newobj.Modules
```

**Comment by secabstraction** [comment]
I should read more closely. I'll go back to my defensive meddling now.

**Comment by PowerShellMafia** [comment]
Fixed but with reservations about having to drop a temp file to disk. Shrug...

**Comment by secabstraction** [comment]
This is ugly...
```powershell
ps -id $PID | % { $thisobj = $_ ; $thisobj | gm -MemberType Property,NoteProperty,ScriptProperty | % { if ($thisobj."$($_.Name)") { $thisobj."$($_.Name)" | ConvertTo-Csv }}}
```

**Comment by PowerShellMafia** [comment]
And it's all text. No type information is preserved.
